# Generated by Django 5.1.2 on 2024-10-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_id', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('piece_length', models.IntegerField()),
                ('pieces', models.IntegerField()),
                ('uploader_id', models.CharField(max_length=255)),
            ],
        ),
    ]
