# Generated by Django 5.1.2 on 2024-10-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('standard_piece_size', models.IntegerField()),
                ('piece_count', models.IntegerField()),
                ('hash_code', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FileAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_pieces', models.JSONField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.file')),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('peer_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('upload_rate', models.FloatField()),
                ('download_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PeerAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.peer')),
            ],
        ),
        migrations.CreateModel(
            name='PeerPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_at', models.DateTimeField(auto_now_add=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.peer')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('piece_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_index', models.BigIntegerField()),
                ('actual_piece_size', models.IntegerField()),
                ('hash_code', models.CharField(max_length=40)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.file')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('sync_id', models.AutoField(primary_key=True, serialize=False)),
                ('sync_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('tracker_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Torrent',
        ),
        migrations.AddField(
            model_name='fileavailability',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.peer'),
        ),
        migrations.AddField(
            model_name='peerpiece',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.piece'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='download_tracker.tracker'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='download_tracker.tracker'),
        ),
        migrations.AddField(
            model_name='fileavailability',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.tracker'),
        ),
    ]
