# Generated by Django 5.1.2 on 2024-10-31 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download_tracker', '0002_file_fileavailability_peer_peerauth_peerpiece_piece_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerpiece',
            name='peer',
        ),
        migrations.RemoveField(
            model_name='peerpiece',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='file',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='target',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='tracker',
        ),
        migrations.RemoveField(
            model_name='file',
            name='piece_count',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.RemoveField(
            model_name='file',
            name='standard_piece_size',
        ),
        migrations.DeleteModel(
            name='FileAvailability',
        ),
        migrations.DeleteModel(
            name='PeerPiece',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
        migrations.DeleteModel(
            name='SyncLog',
        ),
    ]
