# Generated by Django 5.1.2 on 2024-10-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_tracker', '0003_remove_peerpiece_peer_remove_peerpiece_piece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_type', models.CharField(choices=[('leecher', 'seeder')], max_length=10)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.file')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download_tracker.peer')),
            ],
        ),
    ]
