# Generated by Django 5.1.2 on 2024-10-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download_tracker', '0004_peerfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='download_rate',
        ),
        migrations.RemoveField(
            model_name='peer',
            name='upload_rate',
        ),
    ]
