# Generated by Django 5.1.2 on 2024-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_tracker', '0005_remove_peer_download_rate_remove_peer_upload_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AlterField(
            model_name='peer',
            name='peer_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
